// Live layer: sign-in, radar, chat, reports. Loaded after app.js and replaces its demo screens.
const S={token:'',me:null,items:[],mine:[],threads:[],thread:null,tinfo:null,msgs:[],radius:3,loc:null,geo:'',step:'phone',phone:'',name:'',dev:'',err:'',draft:'',report:false,lastPost:0};
try{S.token=localStorage.getItem('nc_token')||''}catch{}
state.offers=[];state.requests=[];state.tx=[];
async function api(p,b){const r=await fetch('/api/'+p,{method:b?'POST':'GET',headers:{'Content-Type':'application/json',...(S.token?{Authorization:'Bearer '+S.token}:{})},body:b?JSON.stringify(b):undefined});const j=await r.json().catch(()=>({}));if(r.status===401&&S.token){logout();throw new Error('Please sign in again')}if(!r.ok)throw new Error(j.error||'Something went wrong');return j}
const fail=e=>toast(e.message),authErr=m=>{S.err=m;render()};
function logout(){S.token='';S.me=null;try{localStorage.removeItem('nc_token')}catch{}S.es&&S.es.close();render()}
function authHtml(){const p=S.step==='phone';return `<div class="auth"><div class="card auth-card"><img class="logo" style="width:56px;height:56px" src="icons/icon-96.png" alt="Near Cash logo"><h1>${p?'Sign in to Near Cash':'Enter your code'}</h1><p>${p?'We text a one-time code to verify your phone.':'Sent to '+esc(S.phone)+'.'}</p>${p?`<label>Your name</label><div class="field"><input id="an" value="${esc(S.name)}" maxlength="40"></div><label>Phone number</label><div class="field"><input id="ap" inputmode="tel" value="${esc(S.phone)}" placeholder="+91 98765 43210"></div><label class="chk"><input type="checkbox" id="aa"> I am 18 or older and will only meet in public places.</label><button class="primary full" onclick="sendOtp()">Send code</button>`:`<label>6-digit code</label><div class="field"><input id="ac" inputmode="numeric" maxlength="6" autocomplete="one-time-code"></div>${S.dev?`<p class="dev">Dev mode code: <b>${S.dev}</b></p>`:''}<button class="primary full" onclick="verifyOtp()">Verify and continue</button><button class="text" onclick="S.step='phone';S.err='';render()">Change number</button>`}${S.err?`<div class="err">${esc(S.err)}</div>`:''}</div></div>`}
async function sendOtp(){S.name=document.getElementById('an').value.trim();S.phone=document.getElementById('ap').value.trim();const ad=document.getElementById('aa').checked;if(!S.name)return authErr('Enter your name.');if(!ad)return authErr('Confirm that you are 18 or older.');try{const j=await api('otp',{phone:S.phone});S.dev=j.devCode||'';S.step='code';S.err='';render()}catch(e){authErr(e.message)}}
async function verifyOtp(){try{const j=await api('verify',{phone:S.phone,code:document.getElementById('ac').value.trim(),name:S.name,adult:true});S.token=j.token;S.me=j.me;try{localStorage.setItem('nc_token',j.token)}catch{}S.err='';boot()}catch(e){S.err=e.message;render()}}
function boot(){state.profile.name=S.me.name;state.screen='home';connect();startGeo();refresh()}
async function refresh(){try{const[n,t]=await Promise.all([api('nearby?r='+S.radius),api('threads')]);S.items=n.items;S.mine=n.mine;S.threads=t.items;state.offers=S.items.filter(x=>x.type==='have').map(x=>({status:'open',expires:Infinity}));state.requests=S.items.filter(x=>x.type==='need').map(x=>({status:'open'}));state.tx=S.threads;
  if(['home','find'].includes(state.screen)||(state.screen==='activity'&&!S.thread))render()}catch{}}
function connect(){S.es&&S.es.close();S.es=new EventSource('/api/stream?token='+S.token);S.es.onmessage=e=>{const j=JSON.parse(e.data);if(j.t==='msg'){if(S.thread===j.threadId){S.msgs.push(j.msg);render();scrollChat()}else toast('New message from '+j.from);refresh()}else refresh()}}
function startGeo(){if(!navigator.geolocation){S.geo='off';return}navigator.geolocation.watchPosition(p=>{const first=!S.loc;S.loc={lat:p.coords.latitude,lng:p.coords.longitude};S.geo='ok';if(first||Date.now()-S.lastPost>15000){S.lastPost=Date.now();api('location',S.loc).then(()=>first&&refresh()).catch(()=>{})}},()=>{S.geo='off';render()},{enableHighAccuracy:true,maximumAge:10000,timeout:20000})}
const geoMsg=()=>S.geo==='ok'?'Live from your location. Others only see approximate distance.':S.geo==='off'?'Location is off. Allow location in your browser to see people nearby.':'Finding your location…';
function setRadius(k){S.radius=k;refresh()}
function matches(){const it=S.items;return `<div><div class="page-head"><div><h1>Live radar</h1><p>${geoMsg()}</p></div><button class="secondary" onclick="go('need')">＋ New post</button></div><div class="opts rad">${[1,3,5].map(k=>`<button class="${S.radius===k?'sel':''}" onclick="setRadius(${k})">${k} km</button>`).join('')}</div><div class="radar-wrap"><canvas id="radar" width="640" height="640" aria-label="Radar of nearby cash"></canvas><div class="legend"><span><i class="d1"></i>Cash available</span><span><i class="d2"></i>Cash needed</span></div></div>${S.mine.length?`<div class="label">Your live posts <span>${S.mine.length}</span></div>${S.mine.map(l=>`<div class="match card"><div class="person">${l.type==='have'?'+':'₹'}</div><div class="match-main"><b>${money(l.amount)}</b><p>${l.type==='have'?'Available':'Needed'} · ${Math.max(1,Math.ceil((l.exp-Date.now())/60000))} min left</p></div><button class="secondary small" onclick="cancelPost('${l.id}')">Cancel</button></div>`).join('')}`:''}<div class="label">Nearby <span>${it.length}</span></div>${it.length?it.map(l=>`<div class="match card" id="c-${l.id}"><div class="person ${l.type==='need'?'blue':''}">${l.type==='have'?'+':'₹'}</div><div class="match-main"><b>${money(l.amount)}${l.type==='need'?' needed':''}</b><p>${esc(l.name)} · ${l.km} km away · ${l.mins} min left</p><div class="rel">${l.done} completed exchanges</div></div><button class="primary small" onclick="openDeal('${l.id}')">${l.type==='have'?'Request':'Offer cash'}</button></div>`).join(''):empty('Nobody within '+S.radius+' km right now.')}</div>`}
function startRadar(){const c=document.getElementById('radar');if(!c)return;const x=c.getContext('2d'),W=640,R=300,cx=320,cy=320,reduce=matchMedia('(prefers-reduced-motion:reduce)').matches;let a=0;
  const pos=l=>{const r=Math.min(l.km/S.radius,1)*R,t=(l.brg-90)*Math.PI/180;return{x:cx+r*Math.cos(t),y:cy+r*Math.sin(t)}};
  c.onclick=e=>{const r=c.getBoundingClientRect(),px=(e.clientX-r.left)*W/r.width,py=(e.clientY-r.top)*W/r.height,h=S.items.find(l=>{const p=pos(l);return Math.hypot(p.x-px,p.y-py)<26});if(h){const el=document.getElementById('c-'+h.id);if(el){el.scrollIntoView({behavior:'smooth',block:'center'});el.classList.add('flash')}}};
  (function f(){if(!c.isConnected)return;x.clearRect(0,0,W,W);x.strokeStyle='rgba(52,224,161,.24)';x.lineWidth=1.5;for(let i=1;i<=3;i++){x.beginPath();x.arc(cx,cy,R*i/3,0,7);x.stroke()}x.beginPath();x.moveTo(cx-R,cy);x.lineTo(cx+R,cy);x.moveTo(cx,cy-R);x.lineTo(cx,cy+R);x.stroke();
    x.fillStyle='rgba(148,170,200,.85)';x.font='20px sans-serif';x.textAlign='left';for(let i=1;i<=3;i++)x.fillText((S.radius*i/3).toFixed(1).replace('.0','')+' km',cx+6,cy-R*i/3+20);x.fillText('N',cx+6,cy-R+2);
    if(!reduce)a=(a+.025)%(Math.PI*2);if(x.createConicGradient){const g=x.createConicGradient(a-Math.PI/2,cx,cy);g.addColorStop(0,'rgba(52,224,161,0)');g.addColorStop(.17,'rgba(52,224,161,.4)');g.addColorStop(.18,'rgba(52,224,161,0)');x.fillStyle=g;x.beginPath();x.arc(cx,cy,R,0,7);x.fill()}
    S.items.forEach(l=>{const p=pos(l),col=l.type==='have'?'#34e0a1':'#4cc9f0';x.fillStyle=col;x.shadowColor=col;x.shadowBlur=18;x.beginPath();x.arc(p.x,p.y,12,0,7);x.fill();x.shadowBlur=0;x.fillStyle='#04141c';x.font='bold 14px sans-serif';x.textAlign='center';x.fillText(l.type==='have'?'+':'₹',p.x,p.y+5)});
    x.fillStyle='#fff';x.beginPath();x.arc(cx,cy,8,0,7);x.fill();requestAnimationFrame(f)})()}
async function cancelPost(i){try{await api('listings/cancel',{id:i});refresh()}catch(e){fail(e)}}
async function openDeal(i){try{const t=await api('threads',{listingId:i});await refresh();openThread(t.id)}catch(e){fail(e);refresh()}}
async function openThread(i){try{const j=await api('threads/'+i);S.thread=i;S.tinfo=j;S.msgs=j.msgs;S.report=false;state.screen='activity';render();scrollChat()}catch(e){fail(e)}}
const scrollChat=()=>{const m=document.getElementById('msgs');if(m)m.scrollTop=m.scrollHeight};
function activity(){if(S.thread)return chatHtml();return `<div class="activity"><div class="page-head"><div><div class="eyebrow">YOUR ACTIVITY</div><h1>Exchanges</h1><p>Chats with people you matched with.</p></div></div>${S.threads.length?S.threads.map(t=>`<div class="tx card"><div class="tx-icon">◷</div><div class="tx-main"><b>${money(t.amount)}</b><span class="status ${t.status==='completed'?'done':''}">${t.status}</span><p>${esc(t.other.name)} · ${t.last?esc(t.last):'No messages yet'}</p></div><button class="primary small" onclick="openThread('${t.id}')">Open chat</button></div>`).join(''):empty('No exchanges yet.')}</div>`}
function chatHtml(){const t=S.tinfo,o=t.other,me=S.me.id,open=t.status==='open';return `<div class="chat"><button class="back" onclick="go('activity')">‹ Exchanges</button><div class="chat-head card"><div class="avatar">${esc(o.name[0]||'?')}</div><div class="match-main"><b>${esc(o.name)}</b><p>${money(t.amount)} · ${o.done} completed · ${esc(t.status)}</p></div></div><div class="notice">✓<div><b>Stay safe</b><span>Meet in a public place. Never share OTPs, UPI PINs or passwords. Near Cash never holds your money.</span></div></div><div class="msgs" id="msgs">${S.msgs.map(m=>`<div class="bub ${m.from===me?'me':''}">${esc(m.text)}<small>${new Date(m.at).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</small></div>`).join('')||'<div class="empty"><b>Say hello</b><span>Agree on a public meeting spot.</span></div>'}</div>${open?`<div class="composer"><input id="msg" maxlength="500" placeholder="Message" value="${esc(S.draft)}" onkeydown="if(event.key==='Enter')sendMsg()"><button class="primary" onclick="sendMsg()">Send</button></div><div class="chat-actions"><button class="secondary small" onclick="finishDeal()">${t.confirmed.includes(me)?'Waiting for '+esc(o.name):'Confirm exchange done'}</button><button class="secondary small" onclick="S.report=!S.report;render()">Report or block</button></div>${S.report?`<div class="opts">${[['scam','Scam'],['harassment','Harassment'],['unsafe','Unsafe'],['other','Other']].map(r=>`<button onclick="sendReport('${r[0]}')">${r[1]}</button>`).join('')}</div>`:''}`:'<p class="closed">This exchange is closed.</p>'}</div>`}
async function sendMsg(){const el=document.getElementById('msg'),text=(el?.value||'').trim();if(!text)return;try{const m=await api('threads/'+S.thread+'/messages',{text});S.msgs.push(m);S.draft='';render();scrollChat();document.getElementById('msg')?.focus()}catch(e){S.draft=text;fail(e)}}
async function finishDeal(){try{await api('threads/'+S.thread+'/complete',{});await openThread(S.thread);refresh()}catch(e){fail(e)}}
async function sendReport(r){try{await api('report',{threadId:S.thread,userId:S.tinfo.other.id,reason:r});S.thread=null;await refresh();go('activity');toast('Reported and blocked. Our team will review it.')}catch(e){fail(e)}}
async function submitForm(kind){const amt=Number((document.getElementById('amt')?.value||'').replace(/\D/g,''));state.amount=String(amt||'');if(!amt||amt>5000)return toast('Enter an amount between ₹1 and ₹5,000.');const mins={'ASAP':30,'Within 30 minutes':30,'Within 1 hour':60,'Today':240,'30 minutes':30,'1 hour':60,'3 hours':180}[state.choice]||60;try{await api('listings',{type:kind==='need'?'need':'have',amount:amt,minutes:mins});await refresh();go('find');toast(kind==='need'?'Your request is live on the radar.':'Your cash is live on the radar.')}catch(e){fail(e)}}
const baseRender=render,baseGo=go,baseProfile=profile;
go=function(s){S.thread=null;S.report=false;baseGo(s)};
profile=function(){return baseProfile().replace(/<\/div>$/,'<button class="secondary full" style="margin-top:12px" onclick="logout()">Log out</button></div>')};
render=function(){const m=document.getElementById('msg');if(m)S.draft=m.value;if(!S.token){A.innerHTML=authHtml();return}baseRender();if(state.screen==='find')startRadar();if(S.thread&&S.draft&&document.getElementById('msg'))document.getElementById('msg').value=S.draft};
if(S.token)api('me').then(j=>{S.me=j;boot()}).catch(()=>{});
setInterval(()=>{if(S.token&&S.me&&!document.hidden)refresh()},20000);
render();
